#!/usr/bin/env bash
# vim: noai:ts=4:sw=4:expandtab
# shellcheck source=/dev/null
# shellcheck disable=2009

###################################################################################
# This script uses lsb_release, lscpu, and glxinfo. make sure they are installed. #
###################################################################################
#
# START OF SCRIPT
#
#
clear ; clear

# Universal variables
# user="${USER}\e[33m@"
user="${USER}@"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 " / " $2}')"
OS1="$(lsb_release -si)"
OS="$(lsb_release -sirc)"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi

# colors
 c1="\e[31m" # Red
 c2="\e[32m" # Light Green
 c3="\e[33m" # Yellow
 c4="\e[34m"  # Calm Blue
 c5="\e[35m" # Violet
 c6="\e[1;36m" # Arch Blue
 c7="\e[37m" # White
 c8="\e[38m" # Sky Blue
 c9="\e[39m" # Light Grey
 c10="\e[30m" # Dark Grey
 c20="\e[0m" # Normal

# Package count for Debian based systems
Packages_dpkg(){

         Packages="$(dpkg -l | grep -c ^i)"
}

# Package count for Arch based systems
Arch_Packages(){

         Packages="$(pacman -Qs | wc -l)"

}

# An Error echo wrapper
err0r()
{

    echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
    echo ""
    exit 86
}

# A Warning echo wrapper
warn()
{
 echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$(tput sgr0)"
 echo ""
}

# A Message echo wrapper
msg()
{
 echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}


echo ""
echo -e "${c6}\t     _ "
echo -e "${c6}\t    / \            __   ___                        "
echo -e "${c6}\t   / _ \  ________/ /  / (_)__  __  ____ __        "
echo -e "${c6}\t  / ___ \/ __/ __/ _ \/ / / _ \/ / / /\ \ /        "
echo -e "${c6}\t /_/   \/_/  \__/_//_/_/_/_//_/\__,_//_\_\         "
echo ""
echo ""
# echo -e "${c6}    \e[1m       /\\ \e[22m"${c4}"\e[1m\t\t"${user}"\e[22m"${c20}$(nmcli general hostname)
echo -e "${c6}    \e[1m       /\\ "${c4}"\t\t"${user}"\e[1m"$(nmcli general hostname)
echo -e "${c6}    \e[1m      /  \\ \e[22m"${c4}"\e[1m\t\tOS:\e[22m" ${c20}"Arch Linux"
echo -e "${c6}    \e[1m     /\\   \\ \e[22m"${c4}"\e[1m\tKernel:\e[22m" ${c20}$Kernel
echo -e "${c4}    \e[1m    /      \\ \e[22m"${c4}"\e[1m\tWindow Manager:\e[22m" ${c20}"i3-gaps"
echo -e "${c4}    \e[1m   /   ,,   \\ \e[22m"${c4}"\e[1m\tCPU:\e[22m"${c20}"Intel i5-4200U @ 1.60GHz"
echo -e "${c4}    \e[1m  /   |  |  -\\ \e[22m"${c4}"\e[1m\tGPU:\e[22m"${c20}"Intel HD Graphics 4400"
echo -e "${c4}    \e[1m /_-''    ''-_\\  \tRAM:\e[22m" ${c20}$RAM
echo -e "${c20}"
echo ""
echo ""
